@Library('jenkins-upstream-library') _

pipeline {
    agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
        }
    }
    parameters {
        string(defaultValue: '', description: 'Enter IPI cluster prefix (Ex: wfk5d )', name: 'ClusterPrefix')
        string(defaultValue: '', description: 'Enter CIS Instance CRN ', name: 'CisCrn')
        choice(description: 'Select workspace/clustername to clean up the resources', choices: ['rdr-cicd-fra1-416', 'rdr-cicd-fra2-416', 'rdr-cicd-mad02-416', 'rdr-cicd-mad04-416', 'rdr-cicd-sao04-416', 'rdr-cicd-wdc06-416', 'rdr-cicd-wdc07-416', 'rdr-cicd-lon06-416', 'rdr-cicd-osa21-416', 'rdr-cicd-sao01-416', 'rdr-cicd-syd04-416'], name: 'ClusterName')
    } 
    environment {
        IBMID="ltccci@in.ibm.com"
        IBMCLOUD_API_KEY=credentials('IBMCLOUD_UPSTREAM_CI_API_KEY_1')
        //VPCREGION= "eu-de"
        RESOURCE_GROUP="ibm-internal-cicd-resource-group"
        BASEDOMAIN="ppc64le-cloud.cis.ibm.net"
        CIS_CRN="${params.CisCrn}"
        CLUSTER_NAME="${params.ClusterName}"
        CLUSTER_PREFIX="${params.ClusterPrefix}"
        CLUSTER_DIR="./ipi-install"
        OPENSHIFT_CLIENT_TARBALL_AMD64="https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest-4.16/openshift-client-linux.tar.gz"
        OPENSHIFT_INSTALLER_URL="https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest-4.16/openshift-install-linux.tar.gz"
	 }
    stages {
        stage('initilize powervs workspace environments') {
            steps {
                script{
                    if (env.CLUSTER_NAME == "rdr-cicd-fra1-416"){
                        env.POWERVS_REGION = "eu-de"
                        env.POWERVS_ZONE = "eu-de-1"
                        env.SERVICE_INSTANCE_GUID = "e6e8ab39-06f3-45c3-b90f-f35088aece99"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-fra2-416"){
                        env.POWERVS_REGION = "eu-de"
                        env.POWERVS_ZONE = "eu-de-2"
                        env.SERVICE_INSTANCE_GUID = "7a6bb29b-7ce2-46b0-923e-81f59aeb8b31"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-mad02-416"){
                        env.POWERVS_REGION = "mad"
                        env.POWERVS_ZONE = "mad02"
                        env.SERVICE_INSTANCE_GUID = "3e283902-54e5-42d4-bc74-82d635a38b78"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-mad04-416"){
                        env.POWERVS_REGION = "mad"
                        env.POWERVS_ZONE = "mad04"
                        env.SERVICE_INSTANCE_GUID = "2e322992-9e36-43db-a017-bcc364bfb4b2"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-sao04-416"){
                        env.POWERVS_REGION = "sao"
                        env.POWERVS_ZONE = "sao04"
                        env.SERVICE_INSTANCE_GUID = "44c283c8-101c-4117-bfd1-3c1e80520aa8"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-wdc06-416"){
                        env.POWERVS_REGION = "wdc"
                        env.POWERVS_ZONE = "wdc06"
                        env.SERVICE_INSTANCE_GUID = "ee746023-4bbe-4bae-b747-e79b3fd229ca"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-lon06-416"){
                        env.POWERVS_REGION = "lon"
                        env.POWERVS_ZONE = "lon06"
                        env.SERVICE_INSTANCE_GUID = "621aec6b-dc3c-4810-a31f-b8dde937ca03"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-osa21-416"){
                        env.POWERVS_REGION = "osa"
                        env.POWERVS_ZONE = "osa21"
                        env.SERVICE_INSTANCE_GUID = "c495676b-2162-4a3f-a7a2-e7fb466c6899"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-sao01-416"){
                        env.POWERVS_REGION = "sao"
                        env.POWERVS_ZONE = "sao01"
                        env.SERVICE_INSTANCE_GUID = "e6a6306b-8348-48dd-99ad-56a7bafc9265"
                    }
                    if (env.CLUSTER_NAME == "rdr-cicd-syd04-416"){
                        env.POWERVS_REGION = "syd"
                        env.POWERVS_ZONE = "syd04"
                        env.SERVICE_INSTANCE_GUID = "2016869c-f03e-425a-9145-3f245b17a2f1"
                    }
                    currentBuild.description = "Cleanup for: ${env.CLUSTER_NAME}-${CLUSTER_PREFIX}"
                }
            }
        }
        //Checkout the installer git repo
        stage('Cleanup cluster') {
            steps {
                script {
                    ansiColor('xterm') {
                        echo ""
                    }
                    try
                    {
                        sh '''
                            mkdir ${WORKSPACE}/destroy-ipi-cluster && cd ${WORKSPACE}/destroy-ipi-cluster
                            curl -sL https://raw.githubusercontent.com/ppc64le-cloud/pvsadm/master/get.sh | VERSION="v0.1.8" FORCE=1 bash
                            wget --quiet "${OPENSHIFT_CLIENT_TARBALL_AMD64}" -O - | tar -xz
                            cp kubectl oc /usr/bin/
                            curl -L "${OPENSHIFT_INSTALLER_URL}" > openshift-install-linux.tar.gz
                            tar -xvf openshift-install-linux.tar.gz  -C /usr/local/bin
                            oc version
                            openshift-install version
                            chmod +x ${WORKSPACE}/scripts/cleanup-ipi-resources.sh && ${WORKSPACE}/scripts/cleanup-ipi-resources.sh
                        '''
                    }
                    catch (err)
                    {
                        echo 'Error ! IPI cluster setup failed !'
                        env.FAILED_STAGE=env.STAGE_NAME
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
